### ISSUE TITLE
Vertex Label with given name does not exist: a

### ISSUE THREAD

**Issue by firepation** [pluradj/janusgraph-remote-java-example#1]
Why did this problem occur after running this program?

```
java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Vertex Label with given name does not exist: a
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at org.apache.tinkerpop.gremlin.driver.ResultSet.one(ResultSet.java:107)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.hasNext(ResultSet.java:159)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:166)
	at org.apache.tinkerpop.gremlin.driver.ResultSet$1.next(ResultSet.java:153)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:142)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal$TraverserIterator.next(DriverRemoteTraversal.java:127)
	at org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteTraversal.nextTraverser(DriverRemoteTraversal.java:108)
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.processNextStart(RemoteStep.java:80)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)
	at pluradj.janusgraph.example.RemoteJavaExample.main(RemoteJavaExample.java:47)
```

**Comment by pluradj** [comment]
I just verified again on my machine that the code works from a clean unzip of the release.

I would guess that you changed the JanusGraph server configuration `gremlin-server.yaml` from the default found in the distribution. If you want to run this example program against a different server configuration, you may need to update the [client configuration files](https://github.com/pluradj/janusgraph-remote-java-example/tree/master/conf) accordingly.
